# Generated by Django 4.0.4 on 2022-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0002_entry_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='shares',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
